AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/3dcb45f6f4fde237940b6ebe8066d57f
      Environment:
        Variables:
          FEEDBACK_URL: https://minsk.gov.by/ru/feedback
      Events:
        HelloWorld:
          Properties:
            Method: post
            Path: /treatment
          Type: Api
      Handler: handler.treatment
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
