AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Globals:
  Function:
    Timeout: 30
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/a3484f1b01614be3d75c5a85b93a1106
      Environment:
        Variables:
          FORM_URL: https://wf36w9xxo1.execute-api.us-east-1.amazonaws.com/Prod/v1
      Events:
        Treatment:
          Properties:
            Method: post
            Path: /v1/treatment
          Type: Api
      Handler: handler.treatment
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TreatmentListFunction:
    Properties:
      CodeUri: s3://jam-be/a3484f1b01614be3d75c5a85b93a1106
      Events:
        Treatment:
          Properties:
            Method: get
            Path: /v1/treatments
          Type: Api
      Handler: handler.list
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
