AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Globals:
  Function:
    Timeout: 30
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/e6f9626736d73fba5b59fef24eae346e
      Events:
        Treatment:
          Properties:
            Method: post
            Path: /v1/treatment
          Type: Api
      Handler: handler.treatment
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TreatmentListFunction:
    Properties:
      CodeUri: s3://jam-be/e6f9626736d73fba5b59fef24eae346e
      Events:
        Treatment:
          Properties:
            Method: get
            Path: /v1/treatments
          Type: Api
      Handler: handler.list
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
