AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Globals:
  Function:
    Timeout: 30
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/62cbd911a5f1613a787c7047da378d3e
      Environment:
        Variables:
          FORM_URL: https://wf36w9xxo1.execute-api.us-east-1.amazonaws.com/Prod/v1
          TABLE_NAME: jam-db
      Events:
        Treatment:
          Properties:
            Method: post
            Path: /v1/treatment
          Type: Api
      Handler: handler.treatment
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
          - '*'
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TreatmentListFunction:
    Properties:
      CodeUri: s3://jam-be/62cbd911a5f1613a787c7047da378d3e
      Environment:
        Variables:
          TABLE_NAME: jam-db
      Events:
        Treatment:
          Properties:
            Method: get
            Path: /v1/treatments
          Type: Api
      Handler: handler.list
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
          - '*'
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
