AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/84937f2033cf2968c12fc0f47b712ee8
      Events:
        Treatment:
          Properties:
            Method: post
            Path: /v1/treatment
          Type: Api
      Handler: handler.treatment
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TreatmentListFunction:
    Properties:
      CodeUri: s3://jam-be/84937f2033cf2968c12fc0f47b712ee8
      Events:
        Treatment:
          Properties:
            Method: get
            Path: /v1/treatments
          Type: Api
      Handler: handler.list
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
