AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    treatment
    Template for treatment

Resources:
    TreatmentFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: handler.treatment
            Runtime: nodejs8.10
            Events:
                Treatment:
                    Type: Api
                    Properties:
                        Path: /v1/treatment
                        Method: post
    
    TreatmentListFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: handler.list
            Runtime: nodejs8.10
            Events:
                Treatment:
                    Type: Api
                    Properties:
                        Path: /v1/treatments
                        Method: get