AWSTemplateFormatVersion: '2010-09-09'
Description: 'submit

  Template for submit

  '
Globals:
  Function:
    Timeout: 30
Resources:
  SubmitFunction:
    Properties:
      CodeUri: s3://jam-be/650db5e630ae9a7d407f3a90806339b3
      Environment:
        Variables:
          FEEDBACK_URL: https://minsk.gov.by/ru/feedback
      Events:
        Submit:
          Properties:
            Method: post
            Path: /v1/submit
          Type: Api
      Handler: handler.submit
      MemorySize: 2048
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
