AWSTemplateFormatVersion: '2010-09-09'
Description: 'submit

  Template for submit

  '
Globals:
  Function:
    Timeout: 30
Resources:
  SubmitFunction:
    Properties:
      CodeUri: s3://jam-be/f95f30d8185c5cc5e6b2bc6264ebf1fc
      Environment:
        Variables:
          FEEDBACK_URL: https://minsk.gov.by/ru/feedback
      Events:
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            Stream: arn:aws:dynamodb:us-east-1:550997613790:table/jam-db/stream/2018-11-24T20:21:34.623
          Type: DynamoDB
      Handler: handler.submit
      MemorySize: 1024
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
          - '*'
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
