AWSTemplateFormatVersion: '2010-09-09'
Description: 'treatment Template for treatment

  '
Resources:
  TreatmentFunction:
    Properties:
      CodeUri: s3://jam-be/6d337c5b325955df2451623694b1046d
      Environment:
        Variables:
          FEEDBACK_URL: https://minsk.gov.by/ru/feedback
      Events:
        Treatment:
          Properties:
            Method: post
            Path: /v1/treatment
          Type: Api
      Handler: handler.treatment
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  TreatmentListFunction:
    Properties:
      CodeUri: s3://jam-be/6d337c5b325955df2451623694b1046d
      Events:
        Treatment:
          Properties:
            Method: get
            Path: /v1/treatments
          Type: Api
      Handler: handler.list
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
