AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    treatment
    Template for treatment

Resources:
    TreatmentFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: treatment/
            Handler: handler.treatment
            Runtime: nodejs8.10
            Environment:
                Variables:
                    FEEDBACK_URL: https://minsk.gov.by/ru/feedback
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /treatment
                        Method: post